import { readFile, writeFile } from 'node:fs/promises'
import { distribution, pathFor } from './scale-common.mjs'
const root = new URL('../', import.meta.url)
const evidence = new URL('results/evidence/scale/', root)
const read = async name => JSON.parse(await readFile(new URL(name, evidence), 'utf8'))
const builds = await read('builds.json')
const localLatency = await read('local-latency.json')
const localSearch = await read('local-search.json')
const escaping = await read('escaping.json')
const production = await read('production.json')
const searchIndex = await read('search-index-summary.json')
const productionSearchDiagnosis = await read('search-wrong-hit-index.json')
const anomalies = []
const groups = []
for (const mode of ['ssr', 'static']) for (const n of [200, 1000, 2000]) {
  const rows = builds.runs.filter(row => row.mode === mode && row.n === n && typeof row.repeat === 'number' && row.repeat <= 3)
  if (rows.length !== 3 || rows.some(row => row.peakRssBytes === null)) throw new Error(`Incomplete timings/RSS for ${mode} N=${n}`)
  const successful = rows.filter(row => row.exitCode === 0)
  groups.push({ mode, n, successfulAttempts: successful.length, failedAttempts: rows.filter(row => row.exitCode !== 0), attemptMetrics: { wallSeconds: distribution(rows.map(row => row.wallSeconds)), peakRssBytes: distribution(rows.map(row => row.peakRssBytes)), outputBytes: distribution(rows.map(row => row.outputBytes)), nuxtBytes: distribution(rows.map(row => row.nuxtBytes)) }, wallSeconds: distribution(successful.map(row => row.wallSeconds)), peakRssBytes: distribution(successful.map(row => row.peakRssBytes)), outputBytes: distribution(successful.map(row => row.outputBytes)), nuxtBytes: distribution(successful.map(row => row.nuxtBytes)), prerenderedRoutes: rows.map(row => row.prerenderedRoutes), prerenderedHtml: rows.map(row => row.prerenderedHtml), exitCodes: rows.map(row => row.exitCode) })
}
for (const mode of ['ssr', 'static']) for (const [small, large] of [[200, 1000], [200, 2000], [1000, 2000]]) {
  const a = groups.find(row => row.mode === mode && row.n === small)
  const b = groups.find(row => row.mode === mode && row.n === large)
  if (!a.successfulAttempts || !b.successfulAttempts) continue
  const pairedReversals = [1, 2, 3].flatMap(repeat => {
    const smallRun = builds.runs.find(row => row.mode === mode && row.n === small && row.repeat === repeat)
    const largeRun = builds.runs.find(row => row.mode === mode && row.n === large && row.repeat === repeat)
    return largeRun.exitCode === 0 && smallRun.exitCode === 0 && largeRun.wallSeconds < smallRun.wallSeconds ? [`run ${repeat}: N=${large} ${largeRun.wallSeconds}s < N=${small} ${smallRun.wallSeconds}s`] : []
  })
  if (pairedReversals.length || b.wallSeconds.min < a.wallSeconds.max || b.wallSeconds.median < a.wallSeconds.median) anomalies.push({ result: `${mode} timing reversal: ${pairedReversals.length ? pairedReversals.join('; ') + '. ' : ''}Fastest N=${large} ${b.wallSeconds.min}s is below slowest N=${small} ${a.wallSeconds.max}s. Medians: N=${small} ${a.wallSeconds.median}s, N=${large} ${b.wallSeconds.median}s.`, expected: 'Brief: larger N never builds faster; rerun and report.', explanation: 'Runs have substantial changing machine load and memory pressure; workload size alone does not explain wall time. Direct reruns are retained in buildRuns. Do not infer scaling from this inversion.' })
}
const searchCounts = localSearch.map(batch => ({ run: batch.run, locale: batch.locale, found: batch.samples.filter(row => row.found).length, missing: batch.samples.filter(row => !row.found).length, total: batch.samples.length }))
for (const locale of ['en', 'de']) {
  const rows = searchCounts.filter(row => row.locale === locale)
  if (rows.some(row => row.total !== 20 || row.found + row.missing !== 20)) throw new Error(`Search totals do not add up to 20 in ${locale}`)
    if (rows.some(row => row.missing)) anomalies.push({ result: `${locale} search completeness: ${rows.map(row => `${row.found}/20`).join(', ')} found over three local runs.`, expected: 'Complete default MiniSearch record set must find all sampled owning pages, including documents 101 and 1000 (DESIGN.md; installed search-engines.md; X401).', explanation: 'Consistent with audit E-A003: indexing is capped at the first 100 enumerated documents per collection/locale. The production index has exactly 100 distinct owning paths per locale. Fuzzy matches for missing tokens are not counted as the owning page.' })
}
anomalies.push({ result: 'Production API and browser find numeric page 500 while page 75 is missing in both locales. The prebuilt index instead contains English sections 01/11 and German sections 01/10, with 100 owning pages per locale.', expected: 'The brief expects the first ~100 pages to be found; that is not numeric ranks 1–100. The prebuilt index and runtime/browser search should represent the same corpus.', explanation: 'The 100-page cap is confirmed. Source enumeration/query order is likely exposing different subsets, but the precise cause is unproved. An earlier pilot had sections 01/10 in both prebuilt locales. Do not infer a stable numeric cutoff or equivalence between the static index and SSR payload.' })
anomalies.push({ result: `Lighthouse mobile changed from 45 in the no-Markdown-opt-in pilot to ${production.lighthouse?.mobilePerformance ?? 'unavailable'} after the opt-in correction; first observed HTML body remained 334,822 bytes and client JS grew only 112 gzip bytes.`, expected: 'Adding server-side agent Markdown work should not itself produce a large client performance improvement. Compare with the earlier pilot.', explanation: 'The Lighthouse runner used the same heavily loaded Mac. Load changed sharply between runs, and Lighthouse/network/cold-start variability is uncontrolled. No performance improvement is inferred from this score difference.' })
const latencyFailures = [...localLatency.results.flatMap(row => row.batches.flatMap(batch => batch.samples)), ...production.latency.samples].filter(row => row.status !== 200 || !row.documentPresent)
if (latencyFailures.length) anomalies.push({ result: `${latencyFailures.length} latency requests returned errors or omitted the owning document.`, expected: 'A correct SSR measurement returns HTTP 200 and the requested token on all requests.', explanation: 'See raw request samples; failed requests are retained and cannot be interpreted as successful render latency.' })
const agentOn = localLatency.results.find(row => row.agent === 'default')
const agentOff = localLatency.results.find(row => row.agent === 'off')
for (const quantile of ['p50', 'p95']) if (agentOff[quantile].median > agentOn[quantile].median) anomalies.push({ result: `Agent off ${quantile} median ${agentOff[quantile].median}ms exceeds default ${agentOn[quantile].median}ms.`, expected: 'Removing Markdown middleware work is expected to reduce render cost; the brief requires unexplained counter-direction results to be reported.', explanation: 'Sequential batches share a changing, heavily loaded machine; scheduling, cache state, and memory pressure are uncontrolled. No middleware speedup or regression is inferred from this inversion.' })
if (escaping.measurements[2].ratioTo1x > 6) anomalies.push({ result: `C082 4x text took ${escaping.measurements[2].ratioTo1x.toFixed(2)}x the 1x time.`, expected: 'C082 claims linear escaping; similar repeated text should take about 4x time at 4x input.', explanation: 'This is an empirical observation on a loaded machine, not an asymptotic proof. Parse is excluded from the timer.' })
for (const run of builds.runs.filter(row => row.exitCode !== 0)) anomalies.push({ result: `${run.mode} N=${run.n} repeat ${run.repeat} exited ${run.exitCode} after ${run.wallSeconds}s.`, expected: 'A completed build must exit zero; failed attempts cannot establish successful build cost.', explanation: `Retained raw log: ${run.evidence[0]}. Static N=2000 logs report JavaScript heap out of memory near Node's heap limit; attribution to a specific library subsystem is unproved. No heap increase, concurrency change, library tuning or workaround applied.` })
const assumptions = [
  'Completed pre-interruption measurements are reused as requested. Resumed attempts follow a host restart (boot time saved in resume-boot-time.log), so cache and machine-load conditions are not matched between the two series.',
  'Each docs page renders the full locale sidebar (100/500/1000 links as N grows). Static HTML repeats that navigation; output and build growth include the demo workload and are not provider-only measurements.',
  'N means total documents across en and de; the unique token is unique within each locale and shared by translation pairs.',
  'Smaller corpora are exact page-content prefixes except for the final related-page link, which wraps to page 1 to keep the reduced fixture navigable.',
  'Build wall time includes generator and Corepack/pnpm startup. Each attempt removes .nuxt, .output, and .ginko first; artifact inspection after /usr/bin/time exits is outside the timer.',
  'Default agent means no content.agent override (static delivery default), with the docs collection explicitly opting into Markdown output; the second Node build changes only content.agent to false. HTML route rules ensure both builds render on each request.',
  'The targeted vue-tsc check overlapped the first local default-agent request batch. All samples are retained; the alternating three-batch medians do not remove all machine-load or cache effects.',
  'Measurements use a loaded Mac with other jobs and desktop apps active; load averages are recorded per build and request batch. Production browser checks overlap portions of the local build series; this is not an isolated benchmark.',
  'Production search API tests 10 distinct tokens in each locale (20 requests). Quantiles use the nearest-rank method and include the first request.',
  'No performance SLA is supplied for C297. Measurements and functional checks inform the reading; passing page checks do not certify a universal 2000-document limit.',
  'The brief overrides the repository convention of committing run JSON. /results/ was added to .git/info/exclude because the root !results/*.json rule otherwise kept scale JSON unignored.',
  'C082 measures the documented public serializer locally on pre-parsed equal-pattern inputs, three runs of 20 serializations per size, with round-trip validation; no private escape function is imported. This pure serializer result is retained across the demo agent-policy correction because it does not use app configuration or content.'
]
const report = { date: new Date().toISOString().slice(0, 10), demo: 'scale', measuredDeployment: { id: 'dpl_CczshJo3Jc7inTjVeapcyVCTDTy1', immutableURL: 'https://ginko-demo-scale-orw9k4806-lupinum.vercel.app', projectId: 'prj_fnxu1xv4hLgURgcufE5v3Zsuk47I' }, package: { version: '1.0.0-beta.10', tarball: 'vendor/lupinum-ginko-content-1.0.0-beta.10-a3e8ef1.tgz' }, corpus: { documents: 2000, locales: { en: 1000, de: 1000 }, sectionsPerLocale: 20, pagesPerSection: 50, words: { min: 896, max: 1944 }, seed: '0x6a09e667 XOR rank' }, machine: builds.machine, builds: groups, buildRuns: builds.runs, searchCounts, localSearch, searchIndex, productionSearchDiagnosis, agentLatency: localLatency, escaping, production, anomalies, assumptions, issues: [...production.issues, 'Reliable production cold-start visibility unavailable; first observed request is retained.', ...(builds.runs.some(row => row.mode === 'static' && row.n === 2000 && row.exitCode !== 0) ? ['Static N=2000 has failed attempts; successful static output size and final route count are unavailable for those attempts. Node heap and library defaults are unchanged.'] : []), 'C082 escaping ratios are local measurements; no hosted microbenchmark or asymptotic proof is claimed.'] }
const fmt = value => Number(value).toFixed(2)
const triple = (summary, scale = 1) => summary.count === 0 ? 'N/A (no successful build)' : `${fmt(summary.median / scale)} [${fmt(summary.min / scale)}, ${fmt(summary.max / scale)}]`
const lines = [
  '# Scale measurement report', '',
  `Production: ${production.baseURL}. Package beta.10, vendor commit a3e8ef1. Corpus: 2,000 documents (1,000 per locale), 20 sections × 50 pages, 896–1,944 words per body. Generator seed is fixed.`, '',
  'Measured production deployment: https://ginko-demo-scale-orw9k4806-lupinum.vercel.app (dpl_CczshJo3Jc7inTjVeapcyVCTDTy1). Saved production measurements are reused; a later Git-triggered deployment is not remeasured.', '',
  'Machine: Apple M1 Pro, 10 logical CPUs, 16 GiB RAM, Node 24.21.0. Other builds and desktop apps were active; initial load was 19.18/18.86/23.09 and about 10.6 GiB swap was in use later. Per-run load is in the JSON. These are loaded-machine observations.', '',
  '## Build growth', '', 'Three clean attempts per N/mode; exit codes are retained in JSON and failures are identified below. Timings/output of failed attempts are not successful build measurements; median [min, max]. Output sizes count file bytes, not disk allocation. macOS /usr/bin/time -l RSS is bytes and measures peak process RSS, not aggregate process-tree memory.', '',
  '| Mode | N total | Wall s | Peak RSS MiB | .output MiB | public/_nuxt KiB | Prerender routes / HTML files |', '| --- | ---: | ---: | ---: | ---: | ---: | --- |',
  ...groups.map(row => `| ${row.mode} | ${row.n} | ${triple(row.wallSeconds)} | ${triple(row.peakRssBytes, 2 ** 20)} | ${triple(row.outputBytes, 2 ** 20)} | ${triple(row.nuxtBytes, 1024)} | ${row.successfulAttempts ? row.prerenderedRoutes.join('/') : 'no final count'} / ${row.successfulAttempts ? row.prerenderedHtml.join('/') : 'partial only'} |`), '',
  'Failed attempts (partial artifacts; wall time is time to failure, not completed-build cost):', '', '| Mode | N | Run | Wall s | Peak RSS MiB | Partial .output MiB | Partial _nuxt KiB | Final routes / partial HTML | Exit |', '| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |',
  ...groups.flatMap(group => group.failedAttempts.map(row => `| ${row.mode} | ${row.n} | ${row.repeat} | ${fmt(row.wallSeconds)} | ${fmt(row.peakRssBytes / 2 ** 20)} | ${fmt(row.outputBytes / 2 ** 20)} | ${fmt(row.nuxtBytes / 1024)} | unavailable / ${row.prerenderedHtml} | ${row.exitCode} |`)), '',
  'Failed-attempt aggregate: median [min, max], not successful build cost:', '', '| Mode | N | Wall s to failure | Peak RSS MiB | Partial .output MiB | Partial _nuxt KiB |', '| --- | ---: | ---: | ---: | ---: | ---: |',
  ...groups.filter(row => row.failedAttempts.length === 3).map(row => `| ${row.mode} | ${row.n} | ${triple(row.attemptMetrics.wallSeconds)} | ${triple(row.attemptMetrics.peakRssBytes, 2 ** 20)} | ${triple(row.attemptMetrics.outputBytes, 2 ** 20)} | ${triple(row.attemptMetrics.nuxtBytes, 1024)} |`), '',
  'Direct reruns (original runs above are never replaced):', '', '| Mode | N | Run | Wall s | Exit |', '| --- | ---: | --- | ---: | ---: |',
  ...builds.runs.filter(row => (typeof row.repeat === 'number' && row.repeat > 3) || row.repeat === 'agent-default').map(row => `| ${row.mode} | ${row.n} | ${row.repeat} | ${fmt(row.wallSeconds)} | ${row.exitCode} |`), '',
  '## Search completeness', '', 'Each of the three local runs queries the documented useContentSearch composable. A hit counts only if it names the owning page; fuzzy hits on other pages do not count. Each locale has exactly 20 findings per run. Browser latency includes a fixed 350 ms observation wait and is not search-engine compute time.', '',
  '| Locale | Run 1 found / missing | Run 2 found / missing | Run 3 found / missing | Total per run |', '| --- | ---: | ---: | ---: | ---: |',
  ...['en', 'de'].map(locale => `| ${locale} | ${searchCounts.filter(row => row.locale === locale).map(row => `${row.found} / ${row.missing}`).join(' | ')} | 20 |`), '',
  'Full production browser findings (saved desktop run; mobile has the same completeness counts). Found means the expected page appears anywhere in the returned hits. Top hit is the first result, not an inferred exact match:', '',
  '| Locale | Token | Expected page | Returned top hit | Found |', '| --- | --- | --- | --- | --- |',
  ...productionSearchDiagnosis.findings.map(row => `| ${row.locale} | ${row.token} | ${row.expectedPage} | ${row.topHit ?? 'none'} | ${row.found ? 'yes' : 'no'} |`), '',
  'Each production locale has 4 owning-page hits, 15 wrong-page-only results, and 1 empty result (20 total). The successful sampled ranks are 1, 25, 50, and 500. This is not a numeric cutoff at rank 100: ranks 75, 99, and 100 fail while rank 500 succeeds. Examples: zq0101 returns page 0001; zq0100 returns page 0500; zq0400 returns page 0460; zq1000 returns no hits. The generated public index has 100 distinct owning pages per locale, but a different English subset from runtime/browser results.', '',
  'Wrong-hit index diagnosis: zq0101 has zero exact-token records and zero owning-page records in both locales of the saved generated index. Its returned page 0001 contains zq0001. Installed defaults enable fuzzy matching at 0.2 and prefix matching. The evidence establishes omitted content followed by a fuzzy alternate; it does not show an indexed exact token losing on ranking. The source enumeration cause of the asset/runtime subset difference remains unproved. No search configuration or library changes were made.', '',
  'Local run 1 findings (all local repeats are retained in JSON):', '',
  '| Locale | Token | Expected page | Returned top hit | Found |', '| --- | --- | --- | --- | --- |',
  ...localSearch.filter(batch => batch.run === 1).flatMap(batch => batch.samples.map(row => `| ${row.locale} | ${row.token} | ${pathFor(row.rank, row.locale)} | ${row.returnedPaths[0] ?? 'none'} | ${row.found ? 'yes' : 'no'} |`)), '',
  '## Agent on/off SSR latency', '', 'Same corpus, two local Node builds, one server at a time. Three batches of 50 full-body requests to five pages. Median [min,max] across batch quantiles; first request retained in every batch. No library tuning.', '',
  '| Agent | p50 ms | p95 ms | Requests |', '| --- | ---: | ---: | ---: |',
  ...localLatency.results.map(row => `| ${row.agent} | ${triple(row.p50)} | ${triple(row.p95)} | 150 |`), '',
  '## Production latency and budgets', '', '| Measurement | Result |', '| --- | ---: |',
  `| SSR requests / pages | 50 / 5 |`, `| p50 ms | ${fmt(production.latency.summary.p50)} |`, `| p95 ms | ${fmt(production.latency.summary.p95)} |`, `| First observed request ms | ${fmt(production.latency.firstRequest.milliseconds)} |`, `| Cold start | Not reliably visible |`, `| First docs-page client JS gzip bytes | ${production.clientJs?.gzipBytes ?? 'unavailable'} |`, `| Lighthouse mobile performance | ${production.lighthouse?.mobilePerformance ?? 'unavailable'} |`, '',
  'Search API latency includes the truncated default index, not a complete 2,000-document index. Fast timings here do not establish full-corpus search performance.', '',
  '| Token | en found / API ms | de found / API ms |', '| --- | --- | --- |',
  ...production.search.filter(row => row.locale === 'en').map(row => { const de = production.search.find(item => item.locale === 'de' && item.rank === row.rank); return `| ${row.token} | ${row.found ? 'yes' : 'no'} / ${fmt(row.milliseconds)} | ${de.found ? 'yes' : 'no'} / ${fmt(de.milliseconds)} |` }), '',
  '## C082 public serializer escaping', '', 'Pre-parsed equal-pattern strings; three runs of 20 serializations each. Round-trip equality checked at each size. Ratios are measurements, not proof of asymptotic complexity.', '',
  '| Input | Bytes | Serialization ms | Ratio to 1x |', '| --- | ---: | ---: | ---: |',
  ...escaping.measurements.map(row => `| ${row.multiplier}x | ${row.inputBytes} | ${triple(row.milliseconds)} | ${fmt(row.ratioTo1x)} |`), '',
  '## Reading', '',
  `Static N=2,000 completed ${builds.runs.filter(row => row.mode === 'static' && row.n === 2000 && typeof row.repeat === 'number' && row.repeat <= 3 && row.exitCode === 0).length}/3 attempts; failed attempts and partial artifacts above cannot establish static build cost. The 2,000-document corpus ${builds.runs.filter(row => row.mode === 'static' && row.n === 2000 && row.exitCode === 0).length === 3 ? 'builds in both modes and serves' : 'has a working SSR build and serves'} through the unchanged beta.10 filesystem provider, but “reasonable” has no stated SLA. The full build, memory, output-size and SSR costs above are the evidence for deciding whether this fits a specific site; the loaded Mac limits conclusions about scaling. Each page repeats the full locale sidebar, so static growth includes that demo workload. Search completeness breaks first: only ${searchCounts[0].found}/20 sampled English tokens and ${searchCounts[1].found}/20 German tokens are found. The production prebuilt index covers only 100 of 1,000 owning pages per locale; its subset also differs from the runtime/browser results, so the cap is not a stable numeric-rank cutoff. Default fuzzy results can obscure the omission. The agent comparison measures the default middleware's request cost, and runtime search API timings include request-time index construction (E-A015, confirmed by reading the installed endpoint); neither is tuned here.`, '',
  '## Anomalies', '', ...anomalies.map(row => `- ${row.result} Expected: ${row.expected} Explanation: ${row.explanation}`), '',
  '## Assumptions and limits', '', ...assumptions.map(row => `- ${row}`), ...report.issues.map(row => `- ${row}`), '',
  '## Evidence', '', '- results/evidence/scale/builds.json and *.log/*.time (including resume-load.log, resume-boot-time.log and resume-boundary.log)' , '- results/evidence/scale/search-wrong-hit-index.json, production-search-index.json and corpus-validation.json', '- results/evidence/scale/local-latency.json, local-search.json, escaping.json', '- results/evidence/scale/production.json, production-claims.json, production-check.log, lighthouse.json, client-js.json', '- results/evidence/scale-playwright/ (desktop/mobile screenshots and failure traces)', '- results/evidence/scale/vercel-*.json and vercel-*.log', '',
  'Pilot failures remain in results/evidence/scale-pilot-no-agent/. An initial overlapping generator invocation, an overly broad app-owned route rule, and a missing collection Markdown opt-in were corrected before the final recorded series; none is a library finding. The incomplete first static 1,000-document pilot was terminated rather than mixed with the corrected configuration.'
]
await writeFile(new URL(`results/${report.date}-scale.json`, root), JSON.stringify(report, null, 2) + '\n')
await writeFile(new URL('results/scale-report.md', root), lines.join('\n') + '\n')
console.log(JSON.stringify({ report: `results/${report.date}-scale.json`, readable: 'results/scale-report.md', anomalies: anomalies.length, searchCounts }, null, 2))
